services:
  # Backend API
  - type: web
    name: hospice-scheduler-api
    env: node
    plan: basic
    buildCommand: cd hospice-scheduler-api && npm install
    startCommand: cd hospice-scheduler-api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  # Frontend
  - type: static
    name: hospice-scheduler-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://hospice-scheduler-api.onrender.com/api 