services:
  # Backend API
  - type: web
    name: hospice-scheduler-api
    env: node
    buildCommand: cd hospice-scheduler-api && npm install
    startCommand: cd hospice-scheduler-api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SNOWFLAKE_ACCOUNT
        value: ERHPAWA-WO05287
      - key: SNOWFLAKE_USER
        value: COMFORTCARETEST
      - key: SNOWFLAKE_PASSWORD
        value: "@RonakRonak1992"
      - key: SNOWFLAKE_WAREHOUSE
        value: COMPUTE_WH
      - key: SNOWFLAKE_DATABASE
        value: HOSPICE_SCHEDULER
      - key: SNOWFLAKE_SCHEMA
        value: PUBLIC
      - key: SNOWFLAKE_ROLE
        value: ACCOUNTADMIN
      - key: JWT_SECRET
        value: "hospice_scheduler_jwt_secret_2024_production"

  # Frontend
  - type: web
    name: hospice-scheduler-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://hospice-scheduler-api.onrender.com/api 